language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
env:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11

matrix:
    exclude:
        - python: "3.3"
          env: DJANGO=1.9
        - python: "3.3"
          env: DJANGO=1.10
        - python: "3.3"
          env: DJANGO=1.11

install:
    - pip install tox-travis

script: tox

after_success:
    - pip install coveralls
    - coveralls
